[ Feat ] 선배 프로필 리스트 API 연결 및 필터링 기능 구현
TEAM-SEONYAK/SEONYAK_CLIENT pull request #137
Opened 2024-07-17 16:16 UTC by yarimu

## #️⃣ Related Issue
Closes #131 

## ✅ Done Task
  - [ ] 선배 프로필 리스트 api 연결
  - [ ] 필터링 기능 구현
  - [ ] 선배 프로필 직무 레이아웃 변경 적용
  - [ ] 이미지까지 api로 받아오는 것으로 로직 변경

## ☀️ New-insight
- 당연했던 부분이긴 한데... 스타일 부분이 같으면 같은 컴포넌트 명을 써도 된다.. 하하핳... 뭐 그리 다 다른 이름을 주었는지..
- 클라단에서 열심히 고민해보는건 좋지만.. 일정 수준이 넘으면 서버 탓도 해보자...

## 💎 PR Point
☑️ 프로필 리스트 카드 컴포넌트가 수정되었습니다! 
기존 직무, 세부직무 다음줄에 연차였던 것이
한 박스로 취급되어 줄이 넘어가면 줄바꿈되도록 바뀌었습니다! 

선배 프로필 리스트를 사용하는 진이는 저랑 같은 컴포넌트를 사용해서 상관없을 것 같고,
후배 프로필 리스트의 경우 필수 변경이 아닌 선배 프로필처럼 글자 수가 많은지 체크해봐야 하고 
그 이외의 선배 프로필 리스트의 경우 저처럼 변경해야할 것 같습니다! 이점 리드님께 보고해두었습니당

- 가장 긴 직무 사진
<img width="371" alt="스크린샷 2024-07-18 오전 1 14 34" src="https://github.com/user-attachments/assets/9a4732aa-c685-470c-a747-73e124da98e2">

## 📸 Screenshot

https://github.com/user-attachments/assets/4df4050f-5c8c-4b43-a676-79824db80858

2024-07-17 18:37 UTC, ijieun approved these changes
token 은 원격 저장소에 들어가지 않도록 꼭 주의해주세요!
api 연결 고생하셨습니다 LGTM 💗

2024-07-17 19:28 UTC, se0jinYoon requested changes
코멘트 확인해주세요 ~

2024-07-17 19:28 UTC, se0jinYoon commented on src/pages/juniorPromise/JuniorPromisePage.tsx
> +  }
p1) 이 부분 hooks > queries.ts 하나 파서 분리해주세요 !
컴포넌트 내부에 서버통신 로직이 들어가 있는 건 좋지 않답니다 ~?

2024-07-17 19:28 UTC, se0jinYoon commented on package.json
> +    "@types/react-query": "^1.2.9",
p1) 이거 왜 설치해줬나요 ?

2024-07-17 20:33 UTC, yarimu commented on src/components/commons/SeniorCard.tsx
> +interface CompanyProps {
와우 덜덜 정신이 나갔었나봐요 감사합니다 반영 완료했습니다!

2024-07-17 20:35 UTC, yarimu commented on package.json
> +    "@types/react-query": "^1.2.9",
리액트 쿼리 설치해야하는 줄 알았습니다... 삭제 처리 완료했습니다..!

2024-07-17 21:14 UTC, yarimu commented on src/pages/juniorPromise/JuniorPromisePage.tsx
> +  }
그렇군요..!! 처음 알았습니다,, 
해당 위치에 seniorProfileQueries.ts 파일로 분리해두고 동작하는지 확인완료하여 푸시 했습니다!! 감사합니다!

2024-07-18 23:18 UTC, se0jinYoon approved these changes

2024-07-18 23:24 UTC, merged