[ Feat ] 실시간 검색 기능 구현
TEAM-SEONYAK/SEONYAK_CLIENT pull request #139
Opened 2024-07-17 16:45 UTC by lydiacho

## #️⃣ Related Issue
Closes #130 

## ✅ Done Task
  - [ ] 학교 검색 
  - [ ] 학과 검색 

## 💎 PR Point

- 학교 검색의 경우, 첫 화면에서 검색창을 누르면, 다른 시트가 열리면서 새로운 입력창에 다시 검색어를 입력해야 하는데요, 검색어를 입력하기 까지 두번이나 입력창을 터치해야 하는 부분에 사용성이 떨어진다고 생각해서, Input 공통 컴포넌트에 autoFocus라는 optional prop을 추가해주어서, autoFocus가 부여된 Input은 렌더링 될 때부터 자동 포커싱 되도록 만들어주었습니다 
- 폐과는 (폐과) 이렇게 뒤에 붙여줬어요. 근데 학과 리스트가 워낙 오랫동안 쌓인 데이터다보니, 중복된 학과명이 많더라고요? (ex- 2000년에 컴공과가 만들어졌다가, 폐지되었다가, 새로 생겼다가, 2008년에 다시 폐지되었다가.. 이런 경우 `컴공과(폐지)`가 두개임!)  -> 이거 때문에 Key 중복 워닝이 학과검색페이지에서 엄청 많이 뜨고 있는데, 이부분 창균이가 중복 데이터 필터링 처리 해준다고 했어요! 추후 해결될 예정입니다 ~ 
- ⚠️ 현재 onChange 이벤트 발생할 때마다 API 요청이 가고 있는데, 추후 프리태스크로 공부했던 throttle 도입해서 최적화할 예정입니다 

## 📸 Screenshot

https://github.com/user-attachments/assets/1fe97e72-9aa6-4141-9f3f-154f9b19ed0e

2024-07-17 19:17 UTC, ckkim817 requested changes
Looks Bad To Me 😤 고생 안하셨습니다

2024-07-18 00:18 UTC, j-nary requested changes
LGTM

2024-07-18 00:18 UTC, j-nary commented on src/pages/onboarding/apis/searchAxios.ts
> +export const univNameAxios = async (univName: string) => {
react-query에 사용되는 함수에 async가 필요한가용? 
api 요청이 반환한 정보를 해석하여 추가적인 작업을 처리해야 하는 경우에만 필요하다고 알고있는데, 해당 부분은 추가적인 작업이 필요없어보입니당!
관련 아티클 첨부합니다:)
[React Query의 queryFn은 언제 async 가 필요할까](https://velog.io/@parkseonup/React-Query%EC%9D%98-queryFn%EC%9D%80-%EC%96%B8%EC%A0%9C-async-%ED%95%A8%EC%88%98%EB%A1%9C-%ED%98%B8%EC%B6%9C%EB%90%98%EC%96%B4%EC%95%BC-%ED%95%A0%EA%B9%8C)

2024-07-18 00:18 UTC, j-nary commented on src/pages/onboarding/components/commonOnboarding/Step학과선택.tsx
> +  const list: DeptType[] = useSearchDeptQuery('이화여자대학교', searchValue);
나중에 navigate state로 바꿔주기!

2024-07-18 00:18 UTC, j-nary commented on src/pages/onboarding/constants.ts
> +  '경영 ・ 비즈니스',
ㅋㅋㅋㅋㅋㅋㅋㅋ제가 상수를 너무 대충 만들옸넹면 >_<감사함니다

2024-07-18 00:28 UTC, lydiacho commented on src/pages/onboarding/apis/searchAxios.ts
> +export const univNameAxios = async (univName: string) => {
너무좋아요

2024-07-18 00:30 UTC, se0jinYoon approved these changes
lgtm 
나중에 리팩하면서 쿼리키 관리하는 거 같이 고민해보아용 요긴하게 관리하는 방법이 많더라요 ~

2024-07-18 00:31 UTC, merged