[ Refactor ] 폴더 분리, 변수명 읽기 쉽게 변경, UI 조정
TEAM-SEONYAK/SEONYAK_CLIENT pull request #217
Opened 2024-08-07 09:17 UTC by ijieun

## #️⃣ Related Issue
Closes #212 

## ✅ Done Task
  - [ ] 예림언니 파트(선배 필터링)와 폴더 분리(파일 이동)
  - [ ] 한눈에 알기 어려웠던 변수명 변경
  - [ ] 어긋난 UI 조정

## ☀️ New-insight

## 💎 PR Point

### 🌿 예림언니 파트(선배 필터링)와 폴더 분리(파일 이동)
저와 예림언니는 후배 약속 신청 파트인 JuniorPromsie 폴더를 같이 사용하고 있었습니다!
하지만 개발을 하며 파일이 점점 늘어나면서, 같은 폴더 내의 많은 파일들 중에서 해당하는 개발 파일을 잘 구분해기 어려워지면서 JuniorPromise 내의 폴더 분리를 결심하게 되었습니다. 
본래 `juniorPromise/components/... `에 있던 것을 `juniorPromise/components/promiseRequest/...` 로 promiseRequest를 생성해 분리했습니다!

### 🌿 한눈에 알기 어려웠던 컴포넌트명 변경
앱잼 기간 동안 애매했던 컴포넌트 이름 변경의 필요성을 느꼈습니다. 따라서 제 개발 파트인 후배 약속 신청의 컴포넌트명을 변경했습니다. 캘린더 기능과 연관된 컴포넌트명은 CustomCalendar, CalendarBottomSheet, CalendarBottomBar 으로, 캘린더 내의 시간과 관련된 명은 TimeList, TimeListBtns으로, 확인 모달과 관련된 명은 CheckModal, CheckModalContent 으로 변경하는 등의 통일성을 주었습니다. 
저의 개발 파트를 담는 가장 상위 컴포넌트(페이지)는 PromiseRequestPage로 변경했습니다.

### 🌿 중복된 제목 컴포넌트 합치기
원래 같은 구조의 제목 컴포넌트 두개를 따로 작성했습니다. 똑같은 구조에 내용만 다르므로 이를 같은 컴포넌트로 합쳤습니다. `<TitleBox num={0} />`  `<TitleBox num={1} />`으로 같은 컴포넌트를 사용하되, 숫자로 구분해서 내용을 다르게 표시하도록 수정했습니다.
    
    
   

## 📸 Screenshot

<img width="374" alt="스크린샷 2024-08-07 오후 5 36 03" src="https://github.com/user-attachments/assets/08faf1f6-297c-4fa5-89e2-586bc8792780">
<img width="375" alt="스크린샷 2024-08-07 오후 6 15 29" src="https://github.com/user-attachments/assets/3e516ed9-2356-4bfa-a4bd-d75a896bf5ef">

<img width="374" alt="스크린샷 2024-08-07 오후 5 36 11" src="https://github.com/user-attachments/assets/3e749ffc-bb2f-41a5-9ee2-c6529e6091de">
<img width="375" alt="스크린샷 2024-08-07 오후 6 16 01" src="https://github.com/user-attachments/assets/d1266d23-38b2-4165-87a4-7809a37c753d">

2024-08-08 10:51 UTC, se0jinYoon requested changes
네이밍을 바꾸니까 훨씬 가독성 있어졌네요 !! 고생했어요 코멘트 확인 부탁드립니다 ~~

2024-08-08 10:51 UTC, se0jinYoon commented on src/pages/juniorPromise/JuniorPromisePage.tsx
> +import PromiseRequestPage from './components/promiseRequest/PromiseRequestPage';
p2) 폴더 분리 너무 좋습니다 ! 제가 모바일웹의 url과 관련해서 .. 고민을 많이하면서 멘토링할 때 멘토님들께 url 분리가 좋은지 조건부 컴포넌트 분리가 좋을지에 대해서 많이 여쭤봤는데요 ! 당근 멘토님께서 Url을 분리할 수 있으면 조건부 처리보단 분리하는게 좋다고 하시더라구요 ! 그래서 지은이 캘린더 부분도 아예 따로 url로 빼서 구현해도 좋을 것 같습니다 ! 
지은이가 구현을 하면서 불편하다고 느꼈던 부분들도 (예림언니와 같은 파일을 쓰지만 분리되어 보이지 않는 컴포넌트들 때문에 지금 폴더를 새로 만든 것 등!) url을 따로 분리하여 구현하게 된다면 좀 더 가독성있게 해결될 거 같아요 ! 어떻게 생각하시나요 ?

2024-08-08 10:51 UTC, se0jinYoon commented on src/pages/juniorPromise/components/promiseRequest/Banner.tsx
> +const Banner: React.FC<SeniorProps> = ({ senior }) => {
p1) 여기 React.FC 타입 지정을 해 준 이유가 있을까요 ? React.FC는 children을 prop으로 넘겨주지 않아도 children을 자동으로 prop이 추가해주기 때문에 사용을 지양해야하는 패턴이에요! 관련 사항들 검색해보면 많이 나올거에요 ! 저희는 각 컴포넌트가 받는 Prop의 타입을 따로 지정해주는 만큼 꼭 써야하는 이유가 없다면 React.FC는 지워줘도 괜찮을 거 같아요 !

참고하면 좋을 만한 아티클 첨부하고 갑니다아 
[React.FC를 지양해야하는 이유](https://riaxo-developer-blog.com/post?_id=65c30d1ad9a90028a339de29)

2024-08-08 10:51 UTC, se0jinYoon commented on src/pages/juniorPromise/components/promiseRequest/Banner.tsx
>    left: 0;
p2) 여기서 Wrapper에 position을 준 이유가 무엇인가요 ! 헤더가 fixed로 잡혀있어서 wrapper가 헤더 높이만큼 가려져서 보이는 이슈때문이라면 position을 쓰지 않아도 padding-top을 주어서 해결할 수 있답니다 !

2024-08-08 10:51 UTC, se0jinYoon commented on src/pages/juniorPromise/components/promiseRequest/CalendarBottomBar.tsx
>    setIsCalendarOpen: React.Dispatch<React.SetStateAction<boolean>>;
p2) setter함수를 그대로 prop으로 넘기게 되면 `자식 컴포넌트에게 외부 데이터 변경의 주도권을 넘겨주는 것` 이기 때문에 좋지 못한 로직이에요 ! 앱잼때는 급해서 넘겼을 수 있지만, 리팩을 진행하게 된다면 해당 부분들을 그대로 넘기지 않고 콜백함수로 한 번 감싸서 넘기면 좋을 것 같습니다아 ~

2024-08-08 10:51 UTC, se0jinYoon commented on src/pages/juniorPromise/components/promiseRequest/ThreeScheduleSelect.tsx
> +const ThreeScheduleSelect: React.FC<ThreeScheduleSelectProps> = ({
p4) 여기 부분 네이밍은 만약 추후에 기획단에서 시간 선택을 3가지가 아닌 4가지 5가지 이렇게 늘리게 되면 해당 부분을 반영할 수 없는 네이밍이라는 생각이 들어요 ! ScheduleSelect나 TimeSelect와 같이 더 포괄적으로 네이밍해보아도 괜찮을 것 같아요!

2024-08-09 08:57 UTC, ijieun commented on src/pages/juniorPromise/JuniorPromisePage.tsx
> +import PromiseRequestPage from './components/promiseRequest/PromiseRequestPage';
저도 url을 분리하는거 찬성합니다!!
옒언니와 명확하게 서로 다른 기능을 가지고 있기도 하고 후배 약속 시간 신청을 URL로 바로 접근할 수 있어서 개발에서도 더 편리할 것 같습니다아!!! 수정해서 커밋하겠슴다!

2024-08-09 09:34 UTC, ijieun commented on src/pages/juniorPromise/components/promiseRequest/Banner.tsx
> +const Banner: React.FC<SeniorProps> = ({ senior }) => {
React.FC를 사용하면 모든 컴포넌트가 기본적으로 children prop을 받을 수 있게되어서 의도치 않은 문제를 일으킬 수 있겠네요!! 아티클 정독하고 배우고 갑니다..🤍 관련된 부분들 수정하겠습니다!

2024-08-09 09:55 UTC, ijieun commented on src/pages/juniorPromise/components/promiseRequest/Banner.tsx
>    left: 0;
제 페이지에서 헤더가 항상 top: 5rem 크기로 지정되어 있기에, 바뀌지 않는 위치여서 위에서부터 5rem 을 고정되게 띄우도록 위치를 지정해줬습니다!!
고정된 위치인 경우일때도 padding-top을 주어서 해결하는게 나을까요??

2024-08-09 09:56 UTC, ijieun commented on src/pages/juniorPromise/components/promiseRequest/CalendarBottomBar.tsx
>    setIsCalendarOpen: React.Dispatch<React.SetStateAction<boolean>>;
다음 리팩토링 과정에서 적용해보겠습니다! 개선할 부분 잡아주셔서 감사합니다!!!

2024-08-09 10:03 UTC, ijieun commented on src/pages/juniorPromise/components/promiseRequest/ThreeScheduleSelect.tsx
> +const ThreeScheduleSelect: React.FC<ThreeScheduleSelectProps> = ({
저번 미미나때 들었던 내용이 기억나네요,,! 기획이 바뀌어도 포괄적으로 내용을 담을 수 있는 이름을 사용하는게 좋다고 했었는데, 적용하겠습니다! 감사합니다!!

2024-08-10 08:48 UTC, se0jinYoon commented on src/pages/juniorPromise/components/promiseRequest/Banner.tsx
>    left: 0;
음 이건 개인 취향 차이일 것 같아요 ! 저는 개인적으로 position을 최소화해서 사용하는 걸 선호해서 (예상치 못하게 Position이 겹치게될 수도 있어서 ! ) 저라면 Padding-top을 사용할 것 같은데, 지은이가 불편함을 안느낀다면 이대로 두어도 괜찮을 것 같아요 !!

2024-08-10 17:52 UTC, lydiacho reviewed
첫 리팩토링 작업!! 너무너무 수고많았습니다 💕
**내 코드는 내가 제일 잘 리팩할 수 있다**는 점을 명심하고 끊임없이 내가 썼던 코드를 뜯어보면서 더 개선할 방법은 없을까? 고민해보면 좋을 것 같아요!! (이미 그렇게 잘 하고 있는 것 같음) 

질문 하나 남겼으니 코멘트 천천히 확인하고 답변 주셔요 ! !

2024-08-10 17:52 UTC, lydiacho commented on src/pages/juniorPromise/JuniorPromisePage.tsx
> +import PromiseRequestPage from './components/promiseRequest/PromiseRequestPage';
p3) 저도 url 분리하는거에 동의합니다 :) 컴포넌트가 작은 단위들로 분리되어있다보니 하나의 폴더에서 관리하기에 너무 방대한 것 같아요. url 분리하면서 pages 하위에 juniorPromiseRequest 디렉토리 만들게 될텐데, 
현재 보면 `promiseRequest > components` 하위에 자잘한 컴포넌트부터 전체 페이지 레이아웃을 잡는 `PromiseRequestPage.tsx` 까지 모든 파일이 들어있는 상태에요. 
저희 폴더구조 컨벤션에 맞추려면 juniorPromiseRequest 의 하위에 `~Page.tsx` 파일을 위치시켜주고, 그 외의 자잘하게 페이지를 구성하는 컴포넌트들만 juniorPromiseRequest > components 디렉토리에 넣어주면 좋을 것 같네요 :)

2024-08-10 17:52 UTC, lydiacho commented on src/pages/juniorPromise/components/promiseRequest/TitleBox.tsx
p2) TitleBox를 여러 곳에서 재사용할 수 있는 형태로 확장시켜준 것 너무 좋아요! 
여기서 한단계 더 확장해볼 수 있을 것 같은데, 

현재 TitleBox 컴포넌트가 존재하는 이유는 
![image](https://github.com/user-attachments/assets/e068c22b-2d21-4c9d-b9fe-6a03f00f5d27)
이렇게 두꺼운 글씨의 title과 작고 흐린 글씨의 description 조합을 이곳저곳에서 쓸 수 있도록 만든 것이잖아요! 

사실 이런 조합은 선약 서비스 전체에서 수도없이 등장하는 조합이에요. 
그래서 promiseRequest 디렉토리 하위가 아닌, 공통 컴포넌트 폴더에 들어가서 이곳저곳에서 쓰일 수 있는 친구예요. 

그럼 지금 당장 이 TitleBox 컴포넌트를 promiseRequest 외의 이곳저곳에서 쓸 수 있을까요? 
불가능해요. 왜냐면 TitleBox 컴포넌트는 `num`이라는 아주 모호한 prop만 받고있고, 
내부에서는 **title, description 텍스트 값을**  SELECT_JUNIOR_TITLE[num]으로 가져오고 있기 때문에, juniorPromise와 무관한 다른 페이지에서는 이 TItleBox를 사용할 수가 없겠죠. 

그럼 이런 경우, 다른 페이지에서도 지은이가 만든 이 TitleBox 컴포넌트를 사용할 수 있게 더 확장하려면 어떻게 수정해야 할까요 ?

2024-08-10 17:52 UTC, lydiacho commented on src/pages/juniorPromise/components/promiseRequest/TimeList.tsx
p3) 요 컴포넌트에서도 지은이가 컴포넌트 2개를 `TitleBox` 하나로 묶어서 재사용하도록 만들어준 것처럼, 묶어줄만한 친구들이 보이네요. 
전반적으로 `morningTimeList` 냐 `afternoonTimeList`냐에 따라 경우가 나뉘고, 각 경우에서 구현되는 코드의 형태는 동일한 것 같은데, 
그럼 `timeList` 같은 하나의 변수로 `morningTimeList`인지 `afternoonTimeList`인지 관리하고, 
그 timeList 변수를 활용해주면 반복되는 코드를 분리할 수 있는 골자가 잡힐 수 있지 않을까요?? 

이 PR 말고 추후 다른 브랜치에서 공통 컴포넌트 분리 리팩토링 작업할 때 한번 고려해보면 좋을 것 같아요 :)

2024-08-12 08:05 UTC, ijieun commented on src/pages/juniorPromise/JuniorPromisePage.tsx
> +import PromiseRequestPage from './components/promiseRequest/PromiseRequestPage';
넘 좋습니다!! 컨벤션에 따라서 그렇게 수정하면 될 것 같네요!! 감사합니다 :>

2024-08-12 08:07 UTC, ijieun commented on src/pages/juniorPromise/components/promiseRequest/Banner.tsx
>    left: 0;
헉 알겠습니다!! 아직은 불편한 점이 안보여서 이후에 필요성을 느끼면 수정해보겠슴다!!

2024-08-12 08:47 UTC, ijieun commented on src/pages/juniorPromise/components/promiseRequest/TitleBox.tsx
헉 그럼 모호했던 num으로 prop을 받는 대신에 title 과 description 값을 prop 으로 받고, TitleBox 컴포넌트를 common component로 빼면 될 것 같네요!! 이 방향으로 수정해보겠습니다!! 🤍

2024-08-12 09:31 UTC, ijieun commented on src/pages/juniorPromise/components/promiseRequest/TitleBox.tsx
한가지 궁금한 점이 생겼는데, 숭언니의 온보딩 페이지에서도 위와 같은 비슷한 형태의 컴포넌트가 이용되더라구요!!
그런데 비슷해보여도 자세히 보면 title 의 글씨체나 gap 간격 등 다른 점이 있는데,
보통 이런 경우에 숭언니는 이것들도 공통 컴포넌트로 합치는 편인가요??

하나의 공통 컴포넌트를 사용하도록 수정하기 위해 prop에 따라 title 의 글씨체나 gap 간격이 달라지도록 구현을 하는게 오히려 개발 리소스가 크다는 생각이 들어서 고민입니당..

2024-08-12 09:46 UTC, ijieun commented on src/pages/juniorPromise/components/promiseRequest/TimeList.tsx
반복되는 코드이기 때문에 morningTimeList인지 afternoonTimeList 인지 조건에 따라 다른 결과를 보여주면 재사용성을 높일 수 있겠군요..! 다음 PR때 적용해보겠습니다!! 감사합니다 ☺️

2024-08-12 13:41 UTC, se0jinYoon approved these changes

2024-08-12 13:42 UTC, merged

2024-08-12 13:43 UTC, lydiacho commented on src/pages/juniorPromise/components/promiseRequest/TitleBox.tsx
마쟈졍답 ~~~~~~!!! 
맞숩니다. 그리고 지은이가 답변 달면 제꺼랑 합쳐보자는 얘기도 하려고 했는데 그 부분까지 야무지게 먼저 얘기해줬네요 최고 ㅎ ㅎ ㅎ

근데 전 스타일 같을거라고 생각했는데 애매하게 조금씩 픽셀값들이 다 다르네요,,, ? 흐음 보통 이런건 통일시켜달라고 부탁해도 될 것 같은데, 아마 담당 디자이너가 달라서 그런 것 같아요. 
그냥 디잔에게 부탁하기보다 저희가 별도로 관리해주는걸로 하죠! 
TitleBox 현재 상태로 수정해준건 너무너무 좋고, 대신 지은이 페이지 내에서만 공통으로 사용하는거니까 
다른페이지의 TitleBox들과 혼용되지 않게 common 폴더 말고 promiseRequest 디렉토리 내부에 넣어주는게 좋을 것 같아요!!

2024-08-12 13:51 UTC, ijieun commented on src/pages/juniorPromise/components/promiseRequest/TitleBox.tsx
넵 미세하게 달라서 고민이었는데 이정도는 디쟌분들한테 통일시켜달라고 해도 되겠군요!!!
PR이 닫혀서 TitleBox 위치 이동은 라우터 분리하는 담 PR에 포함하겠습니다!! 감숭합니다 :)