[ Fix ] 캘린더 UI 사이 간격 조정
TEAM-SEONYAK/SEONYAK_CLIENT pull request #262
Opened 2024-10-01 03:36 UTC by ijieun

## #️⃣ Related Issue
Closes #245

## ✅ Done Task
- [x] 바, 날짜 사이 간격 조정
- [x]  화살표 사이 간격 조정

## ☀️ New-insight

## 💎 PR Point

캘린더 간단하게 수정했습니다!
화살표 위치를 react-calendar__navigation 에 position: relative; 속성을 주고,
하위 속성인 react-calendar__navigation__prev-button 과 react-calendar__navigation__next-button 각각 왼쪽 오른쪽 화살표에 position: absolute; 을 주고 위치를 지정해주어서 위치 적절하게 옮겨주었습니다! 

## 📸 Screenshot

- 이동 전
<img width="372" alt="스크린샷 2024-10-01 오후 12 30 14" src="https://github.com/user-attachments/assets/f3cb7c37-5f06-4077-91a1-309366b5900c">

- 이동 후 
<img width="372" alt="스크린샷 2024-10-01 오후 12 29 40" src="https://github.com/user-attachments/assets/d69fa878-a2c9-40aa-90ab-ea418ab79086">

2024-10-02 15:13 UTC, se0jinYoon requested changes
현재 모바일 뷰를 풀고 보면 아래 두 부분 위치 정렬이 안맞습니다! 해당 부분 확인하고 같이 작업 진행해주세요 ~ 
코멘트 남긴 것도 확인하고 답글달아주세요~

1. 상단바

![image](https://github.com/user-attachments/assets/de5e66cf-7cb1-43a9-8c5c-e861674ca7e5)

2. 시간 리스트 부분
![image](https://github.com/user-attachments/assets/0cf1fa65-5d68-431d-a338-bccece2c43d2)

2024-10-02 15:13 UTC, se0jinYoon commented on src/pages/juniorPromiseRequest/components/CustomCalendar.tsx
> +    color: ${({ theme }) => theme.colors.grayScaleLG2} !important;
p1) 여기 !important를 적용해준 이유가 뭘까요? 현재 해당 코드를 제거해도 disabled date의 색상이 잘 적용되는 것 같은데 확인 한 번해주세요~

2024-10-02 15:13 UTC, se0jinYoon commented on src/pages/juniorPromiseRequest/components/CustomCalendar.tsx
> +    color: ${({ theme }) => theme.colors.grayScaleWhite} !important;
p1) 여기도 Important 사용 확인해주세요! 지금 Important가 4개 쓰여있는 걸로 확인되는데 해당 부분들 다 꼭 필요한 important인지 확인하고 답글 남겨주세요-!

2024-10-07 14:50 UTC, ijieun commented on src/pages/juniorPromiseRequest/components/CustomCalendar.tsx
> +    color: ${({ theme }) => theme.colors.grayScaleWhite} !important;
캘린더 UI 조정과 important 쓰임 확인 후 반영완료했습니다!!

2024-10-07 15:29 UTC, lydiacho requested changes
p1) 스크롤 영역 수정이 필요해보여요! 

현재 캘린더 바텀시트에서 스크롤을 내리면 위에 바텀시트 영역이 이상하게 잡혀버려요! 
![image](https://github.com/user-attachments/assets/7680d528-891b-41d2-83f4-5562fd4e9c02)

디자인 의도대로라면 바텀시트의 헤더 (아래 사진)은 유지되어있는 채로, 그 내부에서만 스크롤이 발생해야 된다고 생각합니다. 스크롤 영역 잡아서 고쳐보면 좋을 것 같아요!
![image](https://github.com/user-attachments/assets/f308e7b2-58a1-4a3c-8d7e-70f6bacb1180)

2024-10-14 13:28 UTC, lydiacho requested changes
1. 캘린더 스크롤 영역 재지정하는 작업에 `date-fns` 라이브러리가 갑자기 왜 필요해진건가유?? 기능 수정사항이 있던 것도 아닌데 말이쥬! 불필요한 라이브러리 설치는 지양해야 해요! 
2. 현재 마지막 커밋에서 빌드에러가 나는 상태예요! 이러면 머지 시 다른 작업물도 다 안돌아가게 될 수 있기 때문에 yarn build 실행해서 빌드에러 잡고 푸시해주세용! !

2024-10-14 13:41 UTC, se0jinYoon requested changes
캘린더 부분을 구현하기 위해 두개의 라이브러리르 쓰는 것은 좋지 않아보여요. 하나로 통일하는 작업이 필요할 것 같아요. 둘 중 어느게 더 구현사항에 잘 맞는지 장단점을 따져서 도입하면 좋을 것 같아요.
스크롤뷰를 구현하기 위해서 도입하기엔 라이브러리가 너무 커서 스크롤 영역을 다시 잡고 구현해보면 좋을 것 같아요.
마지막 커밋에서 빌드에러 나는데 필요한 수정 다 한 후에 yarn build해서 에러 잡고 피알 올려주세요 ~

2024-10-14 13:41 UTC, se0jinYoon commented on src/pages/juniorPromiseRequest/components/CalendarNavigation.tsx
> +        calendarType="iso8601"
p1) 요놈은 뭔가요?

2024-10-14 13:41 UTC, se0jinYoon commented on src/pages/juniorPromiseRequest/components/CalendarTiles.tsx
> +      /* stylelint-disable-next-line order/properties-order */
p1) 이건 왜 막아준거에요?

2024-10-14 15:19 UTC, lydiacho reviewed
이렇게 다른날 누를 때마다 영역이 바뀌어요 ㅠㅠ 
근데 지금 헤더에있는 아이콘을 따로 추출해서 넣어주고 있는 것 같은데, 
혹시 라이브러리 문서 참고해서 그냥 스크롤 영역만 다시 잡아주는 방식은 없었던걸까요?? 그러면 훨씬 어렵지 않고 이런 자잘한 부작용도 없을 것 같은데 . . 

https://github.com/user-attachments/assets/19da0e3b-5188-4a87-8dbd-f1468e5664b7


만약 정 어려우면 그냥 이렇게 해도 괜찮을 것 같구요 ㅠㅠ

2024-10-14 16:38 UTC, lydiacho commented on src/pages/juniorPromiseRequest/components/CustomCalendar.tsx
> +import React from 'react';
코드 예시유 ,  , ?! 

좀더 풀어 설명해보자면
기존에 쓰고있던 바텀시트의 대가리 부분이 있고(회색 짝대기 + 둥근 모서리) 바텀시트 모서리 패딩 내부에 콘텐츠가 들어가는 영역이 있잖아요! 그 콘텐츠가 들어가는 영역에 들어가야될 내용들을 잘 담아주면 바텀시트 대가리부분을 가리면서 삐져나올 이유가 없겠죠? 지금보니까 z index만 설정해줘도 해결 될 것 같기도..

2024-10-16 15:44 UTC, ijieun commented
@se0jinYoon @lydiacho 코리 반영 완료했습니다 확인부탁드립니더!

2024-10-17 10:10 UTC, se0jinYoon commented
> @se0jinYoon @lydiacho 코리 반영 완료했습니다 확인부탁드립니더!

1. date fns ? 그거 라이브러리 안 쓰는 방안으로 수정하신걸까요? 어디를 어떻게 고치는 방식으로 해결했는지 같이 작성해주면 리뷰하기 편할 거 같아요.
2. 현재 모바일뷰 풀었을 때 캘린더 날짜 선택시 동그라미 부분 ? 이 동그라미가 아닌 타원이에요. 확인 부탁드릴게요

<img width="431" alt="image" src="https://github.com/user-attachments/assets/95ec3535-7fb0-4833-a64b-2a912299f846">

3. 시간 부분도 피그마보면 가운데 정렬이 아니라 양옆 패딩값 제외하고 꽉 맞게 들어가야해요. 현재는 양옆 여백이 피그마보다 많이 잡혀있는 거 같아요. (단순 가운데정렬 처리 되어있는 듯 합니다.) 확인 부탁드릴게요~

[피그마]
<img width="317" alt="image" src="https://github.com/user-attachments/assets/ca0f4d4f-73fd-4e34-a248-f4768ab60ea2">

[구현뷰]
<img width="423" alt="image" src="https://github.com/user-attachments/assets/616378f9-fe1f-4e8f-b663-0dfc2f86daff">

위에 사항들 고치기가 어렵다면 그냥 넘어갑시다. 근데 한 번 해결은 해보면 좋을 것 같아요

2024-10-18 07:53 UTC, ijieun commented
@se0jinYoon 

1. date fns
다른 분들이 의견을 주신 것처럼, 캘린더 날짜가 고정되어 보이는 뷰가 어색하게 느껴졌습니다. 또한, 이를 위해 새로운 라이브러리를 설치하는 것은 비효율적이라고 판단하여, date-fns 라이브러리를 설치하기 전 상태로 되돌렸습니다. 대신 바텀시트 손잡이 부분을 제외하고 CustomCalendar만 스크롤 가능하도록 컴포넌트 영역을 재조정했습니다.

2. 이 부분은 이전부터 고민해온 문제였는데, 캘린더 라이브러리의 특성상 모바일 뷰에서 데스크탑 뷰로 화면 너비가 늘어나면 캘린더도 함께 커지며, 선택한 날짜의 타일이 타원형으로 변하는 이슈가 발생했습니다. 선택한 날짜를 원형으로 유지할지, 캘린더 전체 크기를 UI에 맞출지 고민했는데, 코리 받은 것처럼 아무래도 선택된 날짜 버튼이 타원형으로 보이는 것이 더 어색하다고 생각되어 캘린더의 전체 너비를 고정하여 문제를 해결했습니다.

3. 2번과 같은 문제를 해결하기 위해 캘린더 전체 너비를 고정했더니, 데스크탑 뷰에서는 좌우 너비 조정에 한계가 생겼습니다. 이 부분은 혹시 몰라서 디자인 담당자에게 확인을 받았습니다.

4. 격 조정 작업은 완료했습니다.

2024-10-18 16:39 UTC, se0jinYoon commented
> @se0jinYoon
> 
> 1. date fns
>    다른 분들이 의견을 주신 것처럼, 캘린더 날짜가 고정되어 보이는 뷰가 어색하게 느껴졌습니다. 또한, 이를 위해 새로운 라이브러리를 설치하는 것은 비효율적이라고 판단하여, date-fns 라이브러리를 설치하기 전 상태로 되돌렸습니다. 대신 바텀시트 손잡이 부분을 제외하고 CustomCalendar만 스크롤 가능하도록 컴포넌트 영역을 재조정했습니다.
> 2. 이 부분은 이전부터 고민해온 문제였는데, 캘린더 라이브러리의 특성상 모바일 뷰에서 데스크탑 뷰로 화면 너비가 늘어나면 캘린더도 함께 커지며, 선택한 날짜의 타일이 타원형으로 변하는 이슈가 발생했습니다. 선택한 날짜를 원형으로 유지할지, 캘린더 전체 크기를 UI에 맞출지 고민했는데, 코리 받은 것처럼 아무래도 선택된 날짜 버튼이 타원형으로 보이는 것이 더 어색하다고 생각되어 캘린더의 전체 너비를 고정하여 문제를 해결했습니다.
> 3. 2번과 같은 문제를 해결하기 위해 캘린더 전체 너비를 고정했더니, 데스크탑 뷰에서는 좌우 너비 조정에 한계가 생겼습니다. 이 부분은 혹시 몰라서 디자인 담당자에게 확인을 받았습니다.
> 4. 격 조정 작업은 완료했습니다.

1. 오전+오후 시간대가 존재할 경우 스크롤바가 생기면서 전체적으로 스크롤바 크기만큼 옆으로 밀리는 현상이 있었습니다. (특히 모바일뷰 풀었을 때 확연히 보였어요) 
-> 스크롤바 숨김처리해서 해결해두었습니다.

2. 데탑뷰로 화면 너비가 늘어나면서 캘린더가 커지는 이슈 -> 선택된 타일이 타원형으로 잡히는 이슈
-> 캘린더에 `aspect-ratio: 1 / 1` 속성 적용해서 늘 1:1 비율 가질 수 있도록 수정해두었습니다. 타원형 이슈 없어졌어요.

3. 캘린더, 시간 선택 부분 레이아웃 변경
-> 전체적으로 width값이 고정되어 적용되어 있더라고요. 그렇게되면 데탑뷰로 바뀌면서 화면 너비가 커지면 그만큼 내부 값들이 커져야하는데 반영이 안되는 이슈가 생겨요. 따라서 레이아웃에 패딩 적용해주고 내부 값들 width: 100% 주어 해결해두었습니다.
-> 시간 선택 부분에 그리드 사용해서 화면 크기 커질 경우 너비가 그에 맞게 동적으로 반영될 수 있도록 변경해두었어요.

+) 현재 캘린더 날짜 타일들이 피그마뷰와 크기가 다른데 (선택된 부분의 동그라미 크기가 피그마보다 커요) 이건 부가적인 이슈인 것 같아서 따로 작업 안해두었어요. 일단 이 피알 머지하고 해당 부분은 나중에 잡아도 될 것 같습니다 ~

2024-10-18 16:51 UTC, se0jinYoon approved these changes

2024-10-19 04:35 UTC, lydiacho approved these changes

2024-10-21 11:10 UTC, merged