[ Fix ] junior promise 렌더링 에러 해결
TEAM-SEONYAK/SEONYAK_CLIENT pull request #264
Opened 2024-10-01 08:54 UTC by ijieun

## #️⃣ Related Issue
Closes #263

## ✅ Done Task

- [ ] JuniorPromise 코드 순서 재배치

## ☀️ New-insight

`React Router caught the following error during render Error: Rendered more hooks than during the previous render.
`
이 에러는 이전 렌더링과 비교해서 현재 렌더링에서 더 많은 훅이 사용되었다는 것을 알려주는 것이라고 합니다!!
조건부로 훅을 호출하면 이런 에러가 발생할 수 있고, React에서 훅은 항상 동일한 순서로 호출되어야 한다고 하네요 

☀️ 아래 방법들로 해결할 수 있슴다~!
1. 모든 useState 훅을 컴포넌트 최상단으로 이동
2. 조건부 반환 (if (isLoading), if (isError))을 모든 훅 선언 이후로 이동
3. 데이터 처리 로직을 단순화하고 일관성 있게 배치

## 💎 PR Point

JuniorPromise 컴포넌트의 순서를 다음과 같이 재배치 하였습니다. 

1. 모든 상태 훅을 컴포넌트 최상단에 배치
2. useQuery 호출을 조건부 렌더링 밖으로 이동
3. 핸들러 함수들을 상단에 정의
4. 로딩과 에러 상태 처리
5. 데이터 처리
6. 공통 props 객체

## 📸 Screenshot

해결 완료!!

https://github.com/user-attachments/assets/1d01cc0c-77f9-468e-94ff-3d4e89e49102

2024-10-01 18:21 UTC, yarimu approved these changes
빠른 수정 감사합니다💖

2024-10-01 18:21 UTC, yarimu commented on src/pages/juniorPromise/JuniorPromisePage.tsx
> +    },
p3)
```
// 선택 계열 리스트 배열로
  const isFieldSelected = (fieldName: string) => chipFieldName.includes(fieldName);

  const handleChipField = (fieldName: string) => {
    if (isFieldSelected(fieldName)) {
      setChipFieldName((prev) => prev.filter((name) => name !== fieldName));
    } else {
      setChipFieldName((prev) => [...prev, fieldName]);
    }
  };
```
위의 코드를 간단하게 줄여주셨군요..!! 감사합니다!
handleChipField, handleChipPosition Props의 경우만 함수 전체를 props 객체 안으로 넣어주셨는데, 따로 이유가 있으실까요?

2024-10-01 18:21 UTC, yarimu commented on src/pages/juniorPromise/JuniorPromisePage.tsx
> +                }}
p3) return문 내부에 Prop의 내용을 다 적는 걸로 변경하신 이유가 있으실까요?

2024-10-01 19:31 UTC, yarimu requested changes
빠른 수정 감사합니다💖

2024-10-01 19:31 UTC, yarimu commented on src/pages/juniorPromise/JuniorPromisePage.tsx
> +    },
p1)

```
// 선택 계열 리스트 배열로
  const isFieldSelected = (fieldName: string) => chipFieldName.includes(fieldName);

  const handleChipField = (fieldName: string) => {
    if (isFieldSelected(fieldName)) {
      setChipFieldName((prev) => prev.filter((name) => name !== fieldName));
    } else {
      setChipFieldName((prev) => [...prev, fieldName]);
    }
  };
```
오..! 위의 코드를 간단하게 줄여주셨군요..!! 감사합니다!
하지만,, 혹시나 해서 제가 브랜치 들어가서 작동해봤는데 선택된 칩 삭제 기능이 작동되지 않더라구요,, 지은님이 제안해주신대로 return문 외부 정리하고 Props 들은 기존대로 두는 것 어떻게 생각하시나요..? 위 코드 아이디어대로 제가 잘 작동하도록 리팩토링 브랜치에서 녹여보겠습니다..! 똑같은 일 두번 시키는 것 같아 위 방법대로 다시 정리한 juniorPromisePage 코드 정리해둔 노션 링크 첨부하겠습니다..! 아래 링크의 코드대로 실행해 보았을때 모두 잘 작동했습니다..! 감사합니다

https://yarimu.notion.site/10c1b8fbb0fb80cb994ec03e1b8ea268?pvs=4

2024-10-01 19:31 UTC, yarimu commented on src/pages/juniorPromise/JuniorPromisePage.tsx
p2) import문 10번째줄이랑 18번째줄 같은 파일 같은에 한 번 확인 부탁드림다!

2024-10-01 19:37 UTC, yarimu commented on src/pages/juniorPromise/JuniorPromisePage.tsx
> +    },
- 삭제 기능 동영상입니다!

https://github.com/user-attachments/assets/e37afb28-d946-4939-a734-c07324c18170

2024-10-02 08:04 UTC, yarimu approved these changes
지은이 허락 받고 푸시한 렌더링 에러 해결한 최종 코드입니다..! (댓글로 첨부한 바텀시트 내부 칩 오류도 해결완)

2024-10-02 08:05 UTC, yarimu commented on src/pages/juniorPromise/JuniorPromisePage.tsx
해결완

2024-10-02 08:05 UTC, yarimu commented on src/pages/juniorPromise/JuniorPromisePage.tsx
> +    },
해결완

2024-10-02 15:25 UTC, se0jinYoon approved these changes
lgtm 굿굿
과정 정리 됐으면 주석들은 지워주세요!!

2024-10-07 15:08 UTC, lydiacho approved these changes
수고하셨습니다 👍 

이번에 트러블슈팅하면서 알게된 내용 굉장히 중요한 부분이니까 앞으로 꼭꼭 챙기길 바래요! 
리액트 훅은 절대 조건부 내에서 작동할 수 없고, 무조건 리액트 컴포넌트 혹은 커스텀 훅의 **최상단**에서만 호출될 수 있습니다. 
대표적인 안티패턴으로 인해 발생한 오류이니 앞으로 요 부분 반드시 주의해주세요 ~~!!

2024-10-07 15:09 UTC, merged