[Init]stylelint 초기세팅
TEAM-SEONYAK/SEONYAK_CLIENT pull request #3
Opened 2024-06-30 10:30 UTC by yarimu

---
name: "PR Template"
about: ''
title: "🚀 [Feat] 🐛 [Bug] ♻️ [Refactor] "
labels: ''
assignees: ''

---

| 항목      | 내용                          |
| --------- | ----------------------------- |
| ⏰ Time | 3H 30M           |
| 🌱 Page |  메인페이지 버튼 컴포넌트                |
| #️⃣ Issue Number | #2                 |

## ☀️ New-insight

## ⁉️ Question

## 📸 Screenshot

2024-07-01 11:06 UTC, se0jinYoon requested changes
의존성 워닝 뜨는 거 만 확인 부탁드릴게요 -!

2024-07-01 14:14 UTC, ijieun approved these changes
커밋을 자세히 잘하셨네요!! 고생했우요!!

2024-07-01 15:20 UTC, lydiacho reviewed
스타일 순서 잘먹네요~~ 수고하셨습니다 

style lint 세팅도 settings.json에 어떤거 넣어줘야 저장 시 자동 fix되는지 같은 것들 PR에 같이 다뤄주면 좋을 것 같아요 :)

2024-07-01 15:20 UTC, lydiacho commented on package.json
> +    "styled-components": "^6.1.11"
저희 styled-components말고 emotion사용하기로 했으니까 이 패키지는 다시 지워주면 좋을 것 같아용!

2024-07-01 16:43 UTC, yarimu commented on package.json
> +    "styled-components": "^6.1.11"
아하..!! styled-components는 필요가 없군요..! 덕분에 알았어요 감사합니다!! 
제가 emotion을 처음 사용해서 둘 다 필요한줄 알았습니다.. 하핳!
그 둘 차이를 공부해서 트슈 작성중입니다! 

styled-components 제거 완료했습니당! ☺️

2024-07-01 17:11 UTC, yarimu commented on package.json
> +    "styled-components": "^6.1.11"
해당 부분 pr에 담아서 수정 완료했습니당!😄

감사합니다!!

2024-07-03 10:52 UTC, se0jinYoon approved these changes

2024-07-03 10:57 UTC, merged