[ Feat ] 공통 모달 구현
TEAM-SEONYAK/SEONYAK_CLIENT pull request #36
Opened 2024-07-08 14:21 UTC by se0jinYoon

## #️⃣ Related Issue
Closes #30 

## ✅ Done Task
  - [x] 버튼 눌러서 닫히는 모달 구현
  - [x] 바깥 클릭시 모달 닫히도록 구현
  - [x] 2초 후에 자동으로 닫히는 모달 구현

## ☀️ New-insight

## 💎 PR Point

모달에 두 가지 타입이 있어서 분리해서 만들어두었어요

### ✅ `BtnCloseModal` 버튼 눌러서 닫히는 모달
<img width="197" alt="스크린샷 2024-07-08 오후 11 06 23" src="https://github.com/TEAM-SEONYAK/SEONYAK_CLIENT/assets/109661444/cf62d50d-556c-43e3-8480-77135d8d0f6b">

> 📍 넘겨줘야 하는 것
```typescript
interface BtnCloseModalPropType {
  title: string;
  showModal: boolean;
  handleShowModal: (type: boolean) => void;
  children?: React.ReactNode;
  btnText: string;
}
```
1️⃣ title: 모달 최상단 내용
2️⃣ showModal: 상위 컴포넌트에서 모달을 보여주는 여부에 대한 state를 선언한 후 내려주시면 돼요
3️⃣ handleShowModal: setter함수를 그대로 내려주는게 아니라 한 번 감싸서 내려주시면 돼요
4️⃣ children: 모달 사진을 보면 회색 네모박스 부분에 어떤게 들어갈지는 모달에 따라 다르다고해요. 해당 부분 구현하시고 children으로 넘겨주시면 됩니다
5️⃣ btnText: 버튼에 작성되는 텍스트 넘겨주시면 됩니다

### 📍 사용 예시
```tsx
  const [showModal, setShowModal] = useState(false);

  const onClickBtn = () => {
    setShowModal(true);
  };
  const handleShowModal = (type: boolean) => {
    setShowModal(type);
  };

  return (
    <>
      <button onClick={onClickBtn}>모달 여는 버튼</button>
      <BtnCloseModal
        showModal={showModal}
        handleShowModal={handleShowModal}
        title="약속 잡기 전 주의해주세요"
        btnText="확인했어요"
      />
    </>
  );
};
```

### 📍 useClickOutside 커스텀훅
모달 바깥 부분을 클릭할 경우 모달이 꺼져야 하기 때문에 해당 부분 커스텀 훅으로 구현하였습니다.

커스텀훅을 그냥 실행시키면 모달을 여는 버튼 영역 조차 모달의 바깥영역으로 인식해서 모달이 안 열리는 이슈가 발생하기 때문에,
모달이 열린 후에 커스텀 훅을 실행시키기 위한 state를 추가해두었습니다
```typescript
  // 커스텀 훅 활성화용 state
  const [modalBgClickActive, setModalBgClickActive] = useState(showModal);

  // 커스텀 훅 전달 함수
  const handleOutSideClick = () => {
    if (showModal) {
      setModalBgClickActive(true);
    }
    if (modalBgClickActive) {
      handleShowModal(false);
      setModalBgClickActive(false);
    }
  };

  // 커스텀 훅 사용
  useClickOutside(modalRef, handleOutSideClick);
```

### ✅ 2초 후에 닫히는 모달 
![스크린샷 2024-07-08 오후 11 16 23](https://github.com/TEAM-SEONYAK/SEONYAK_CLIENT/assets/109661444/e406e5c1-4210-4fc1-9ebc-f550de04ed11)

- 해당 모달은 따로 닫히는 동작을 일으키는 부분이 없고, 모달이 뜬 후 2초 후에 자동으로 모달이 닫혀야 합니다.
(바깥 영역 눌러도 꺼지면 안됨)
따라서 useEffect와 타이머를 이용해서 자동으로 모달이 꺼지도록 구현해두었습니다.
- 해당 모달의 회색 부분에는 모달마다 다른 이미지가 들어갈 예정입니다. 크기는 고정되어 있지만 어떤 이미지가 들어가야할지는 미정이라, children으로 넘겨받도록 연결해두었습니다.

> 📍넘겨줘야 하는 것
```typescript
interface AutoCloseModalPropType {
  text: string;
  showModal: boolean;
  handleShowModal: (type: boolean) => void;
  children: React.ReactNode;
}
```
1️⃣ text: 모달에 들어가는 텍스트
2️⃣ showModal: 상위 컴포넌트에서 모달을 보여주는 여부에 대한 state를 선언한 후 내려주시면 돼요
3️⃣ handleShowModal: setter함수를 그대로 내려주는게 아니라 한 번 감싸서 내려주시면 돼요
4️⃣ children: 들어가게 될 이미지 전달해주시면 됩니다.

### 📍 사용예시
```tsx
// 상위 컴포넌트
  <AutoCloseModal showModal={showModal} text="인증에 성공했어요" handleShowModal={handleShowModal}>
    <Img />
  </AutoCloseModal>

// 예시 이미지
const Img = styled.div`
  width: 100%;
  height: 17.1rem;

  background-color: ${({ theme }) => theme.colors.grayScaleMG1};
`;
```

## 📸 Screenshot

https://github.com/TEAM-SEONYAK/SEONYAK_CLIENT/assets/109661444/0c6c404d-aec5-42ba-af74-61458797d8fb

https://github.com/TEAM-SEONYAK/SEONYAK_CLIENT/assets/109661444/de230d87-51ed-4f0f-a522-4aa0e8c445f9

2024-07-09 08:31 UTC, yarimu commented on src/components/commons/modal/BtnModal.tsx
> +      <BtnModalWrapper ref={modalRef}>
p5) useref에 대해 찾아보긴했는데, 이 부분은 어떤 역할을 하는지 아직 감이 안옵니다..! 혹시 알려주실 수 있으실까요..? 감사합니다

2024-07-09 08:31 UTC, yarimu approved these changes

2024-07-09 08:32 UTC, yarimu approved these changes
수고하셨습니다! 
깔끔한 코드 깔끔한 pr 배울 거 천지였습니다...
감사합니다😀

2024-07-09 13:49 UTC, j-nary approved these changes

2024-07-09 13:49 UTC, j-nary commented on src/components/commons/modal/BtnModal.tsx
> +export const BtnCloseModal = (props: BtnCloseModalPropType) => {
해당 컴포넌트는 버튼 클릭했을 때 뜨는 모달같은데 네이밍만 보면 모달 닫는 버튼을 구현한 것 같아 보입니당!! `ToggleModalView` 와 같은 네이밍은 어떻게 생각하세용?
다른 코드들 넘 갓벽했습니당 !! 고생 많으셨어용 :) 특히 ref 이용해서 modal 직접 구현한 부분보고 많이 배워갑니다 !!

2024-07-09 13:58 UTC, lydiacho requested changes
현재 backdrop 클릭 로직을 구현하기 위해 
- Modal 영역이 아닌 곳인지 체크 
- useEffect을 활용 

이렇게 구현되고 있는데요! 
사실 사용자의 액션으로 인해 발생하는 이벤트는 useEffect를 통해 구현하는 것을 최대한 지양해야 한다고 해요
따라서 커스텀훅을 사용하지 않는 방향으로 가는 것이 좋을 것 같은데, 
그러기 위해 `Modal 영역이 아닌 곳인지 체크` 하지 않고, 그냥 모달의 backdrop이 되는 어두운 영역을 모달 아래에 하나 더 깔아서 positon, z index를 통해 겹쳐서 배치시켜주고, 그 backdrop에 클릭 핸들러를 붙이면 될 것 같아요! 

한번 이런 방식으로 구현해보셔도 좋을 것 같아요 :) 👍🏻

2024-07-09 13:58 UTC, lydiacho commented on src/assets/svgs/index.tsx
> +export { default as CloseIc } from './ic_close.svg?react';
p1) 요거 똑같은거 중복으로 들어간 것 같아요!

2024-07-09 13:58 UTC, lydiacho commented on src/components/commons/modal/BtnModal.tsx
> +  handleShowModal: (type: boolean) => void;
```suggestion
  isModalOpen: boolean;
  handleModalOpen: () => void;
```

p3) 전에도 남겼던 코리인데, boolean prop 네이밍은 요런식으로 Is~ 이렇게 하는거 어때요?? 
비슷하게 handler 이름도 바꿔봤어요!

2024-07-09 13:58 UTC, lydiacho commented on src/components/commons/modal/BtnModal.tsx
> +  };
p3) 지금 보면 BtnModal 컴포넌트 안에서는 showModal state를 `false` 처리 시켜주는 친구밖에 없는데요! 
(당연해요 모달 내에서 모달을 켜는 행위는 할 수 없으니까요!) 

따라서 이렇게 여러번 중첩해서 처리해주지 말고, 
아예 prop 이름을 `handleCloseModal` 로 하고, 전해줘야하는 핸들러 함수 내에서 `setShowModal(false)`를 해줘서, 
모달에서는 이렇게 따로 한번 더 핸들러를 만들어줄 필요 없이, 아래에 onClick에서 `handleCloseModal` 만 바로 넣어줄 수 있게 해줘도 될 것 같아요!

2024-07-09 14:41 UTC, se0jinYoon commented on src/components/commons/modal/BtnModal.tsx
> +  };
오 저는 보통 inline에서 바로 콜백함수를 넣는 부분을 지양하는 편인데, 그 이유는 현재는 onClick을 할 때 발생해야 하는 이벤트가 하나 뿐이지만 동작이 추가되는 경우가 발생한다면 결국 언젠간 handler함수를 만들어줘야 하므로 유지보수에 안좋다고 생각해서인데요 ! 이 부분에 대해서 어떻게 생각하시나요 !

2024-07-09 15:29 UTC, ijieun approved these changes
깔끔한 코드와 자세한 PR 덕분에 이해하기가 좋았어요!!
배워갑니다 👍

2024-07-09 15:29 UTC, lydiacho commented on src/components/commons/modal/BtnModal.tsx
> +  };
확장성 측면을 고려하면 그런 방법도 좋은 것 같아요! 제 방법은 확장성보다 사용가능한 범위를 제한시킴으로써 예상 못하는 케이스를 방지할 수 있다는 장점이 있는데요, 
확장성을 중시해서 해당 방식으로 구현했다면 너무너무 좋습니다!!~~~

2024-07-10 08:23 UTC, lydiacho approved these changes

2024-07-10 08:27 UTC, merged