[ Feat ] 구글 소셜 로그인 구현
TEAM-SEONYAK/SEONYAK_CLIENT pull request #42
Opened 2024-07-08 19:15 UTC by j-nary

## #️⃣ Related Issue
Closes #12 

## ✅ Done Task
  - [x] 구글 소셜 로그인 구현
  - [x] accessToken 받아오기
  - [x] accessToken -> localStorage에 저장하기
  - [x] axios baseURL 설정
  - [x] Authorization 필요한 axios header 자동화
  - [ ] COOP 해결 (GG)

## ☀️ New-insight

* accessToken을 받아서 전달하면 되는 줄 알았는데 그러면 보안상에 문제가 생긴다고 했다. `flow: 'auth-code'` 만 추가해주면 accessToken 전 인가코드를 받을 수 있다!
* [https://velog.io/@kingmong/vite.config.ts-설정에서-환경변수-사용하기](https://velog.io/@kingmong/vite.config.ts-%EC%84%A4%EC%A0%95%EC%97%90%EC%84%9C-%ED%99%98%EA%B2%BD%EB%B3%80%EC%88%98-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0)

- Vite에서 기본적으로 `.env` 파일을 읽어오지 않는다!
    - 환경변수들을 자동으로 `process.env` 객체에 로드 X
    - `process.env` 객체를 사용할 수는 있지만, 사용자가 정의한 `.env` 파일에 포함된 환경 변수들은 사용 X
    - 반드시 사용해야하는 경우에는 `loadEnv` 헬퍼를 사용하라그래서 `loadEnv` 사용했습니당
    - vite 공식문서에 설명 잘 나와있더라구요~
      [[Vite 설정하기](https://ko.vitejs.dev/config/#using-environment-variables-in-config)](https://ko.vitejs.dev/config/#using-environment-variables-in-config)
- `GoogleOAuthProvider` 는 최상위컴포넌트에서 사용해야하더라고요! 그냥 Login 컴포넌트에 감쌌다가 트러블 슈팅 꽤나 했습니다.
- 서버 오류날 때 클라이언트에서 직접 api 테스트하는 방법을 마스터했습니다. 너무 길어서 이건 노션 링크 첨부합니다. [서버 이슈있을 때 클라에서 대처하는 방법](https://jnary.notion.site/2e33b9b68ff04a169d7323095a9b0560?pvs=4)

## 💎 PR Point

여러분 자신의 API 명세서에 Authorization이 필요하다! 하면 -> `authAxios` 를 사용해주세요!
그리고 axios `import axios from 'axios';` 이거 가져오지말고 `import { axios } from '../../../../utils/apis';` 이거 가져와서 사용해주세요!

## 📸 Screenshot

2024-07-09 08:55 UTC, se0jinYoon reviewed
구글로그인이 초면이라 많이 배우고 갑니다 ! 코리 한 번만 확인해주세요~

2024-07-09 08:55 UTC, se0jinYoon commented on vite.config.ts
> +  };
p1) 오호 이 부분 환경변수 불러올 때 저는 그냥
`.env`파일에  `VITE_BASE_URL = '~~~'` 와 같은 형식으로 생성해두고, 
사용하는 곳에서 `const baseUrl = import.meta.env.VITE_DEV_BASE_URL; `로 불러와서 사용했는데 

위와같이 작성해야하는 이유가 있나요?

2024-07-09 20:51 UTC, ijieun approved these changes
구글 로그인이 생소했을텐데도 잘 구현 해내셨네요!!
깔끔한 코드 잘 보고 공부하고 갑니다 :> 👍

2024-07-09 20:51 UTC, ijieun commented on src/utils/apis/index.ts
> +      config.headers.Authorization = 'Bearer ${accessToken}';
p1) 토큰 설정 문자열을 '로 사용한 이유가 있나요? 특별한 이유가 없다면 템플릿 리터럴 사용할 때 백틱(`)을 사용해주세요!!
```suggestion
      config.headers.Authorization = `Bearer ${accessToken}`;
```

2024-07-09 20:51 UTC, ijieun commented on src/pages/onboarding/commons/hooks/useLoginQuery.ts
> +      localStorage.setItem('accessToken', data.data.data.accessToken);
p4) localStorage는 클라이언트 측에서 쉽게 접근할 수 있는 저장소라서, XSS공격 등에 취약할 수 있다고 하네요!
가능하면 사용하지 않는 것이 좋다고 합니다.

이를 방지하기 위해 추후 스프린트에 httpOnly 쿠키를 사용하는 것도 좋을 것 같아요!
httpOnly 속성이 설정된 쿠키는 클라이언트 측 JavaScript 코드에서 접근할 수 없기 때문에, XSS 공격에 의해 토큰이 노출되는 것을 방지할 수 있다고 합니다!

- LocalStorage와 Cookies를 비교해놓은 글 공유할게요!!
https://velog.io/@do_dam/LocalStorage-vs.-Cookies-JWT-%ED%86%A0%ED%81%B0%EC%9D%84-%EC%95%88%EC%A0%84%ED%95%98%EA%B2%8C-%EC%A0%80%EC%9E%A5%ED%95%98%EA%B8%B0-%EC%9C%84%ED%95%9C-%EB%B0%A9%EB%B2%95

2024-07-10 16:22 UTC, lydiacho requested changes

2024-07-10 16:22 UTC, lydiacho commented on vite.config.ts
> +      },
p1) 이거 혹시 왜 설정해줬을까유 CORS때문에? 이거 빼줍시당 우회하는 법이라 어차피 배포하면 소용 없어지는 친구들입니다!

2024-07-10 19:21 UTC, j-nary commented on src/utils/apis/index.ts
> +      config.headers.Authorization = 'Bearer ${accessToken}';
헐 이런 걸 캐치해주시다니! 가문의 영광임둥! 오타였슴둥!

2024-07-10 19:22 UTC, j-nary commented on src/pages/onboarding/commons/hooks/useLoginQuery.ts
> +      console.log('Access Token:', data.data.data.accessToken);
넵!! 알겟슴둥!!

2024-07-10 19:22 UTC, j-nary commented on src/pages/onboarding/commons/hooks/useLoginQuery.ts
> +    redirect_uri: 'https://api.seonyak-dev.kro.kr/login/oauth2/code/google',
넹 알겟슴둥!

2024-07-10 19:23 UTC, j-nary commented on vite.config.ts
> +      },
사용하는 곳에서 /api 적으면 BASE_URL 자동으로 삽입될 수 있도록 해준 아이였어용!!

2024-07-10 19:33 UTC, j-nary commented on vite.config.ts
> +  };
저의 아티클 baseURL 설정에 적혀있슴둥 !!
제가 특별히 복사붙여넣기 해드립죠

1. `vite.config.ts` 설정에서 `.env` 환경변수 사용
    
    [https://velog.io/@kingmong/vite.config.ts-설정에서-환경변수-사용하기](https://velog.io/@kingmong/vite.config.ts-%EC%84%A4%EC%A0%95%EC%97%90%EC%84%9C-%ED%99%98%EA%B2%BD%EB%B3%80%EC%88%98-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0)
    
    - Vite에서 기본적으로 `.env` 파일을 읽어오지 않는다!
        - 환경변수들을 자동으로 `process.env` 객체에 로드 X
        - `process.env` 객체를 사용할 수는 있지만, 사용자가 정의한 `.env` 파일에 포함된 환경 변수들은 사용 X
    - 반드시 사용해야하는 경우에는 `loadEnv` 헬퍼를 사용
        
        ```jsx
        import react from '@vitejs/plugin-react';
        import { defineConfig, loadEnv } from 'vite';
        import svgr from 'vite-plugin-svgr';
        
        // https://vitejs.dev/config/
        export default defineConfig(({ mode }) => {
          const env = loadEnv(mode, process.cwd());
        
          return {
            plugins: [react(), svgr()],
            server: {
              port: 5173,
              proxy: {
                '/api': {
                  target: env.VITE_APP_API_BASE_URL, // 로드한 환경 변수를 사용
                  secure: false,
                  changeOrigin: true,
                },
              },
            },
          };
        });
        
        ```
        
    - vite 공식문서에 설명 잘 나와있더라구요~
        
        [[Vite 설정하기](https://ko.vitejs.dev/config/#using-environment-variables-in-config)](https://ko.vitejs.dev/config/#using-environment-variables-in-config)

2024-07-11 15:08 UTC, j-nary commented on vite.config.ts
> +      },
관련 아티클 첨부하겠씁니당
[Proxy-with-vite](https://velog.io/@jeong_woo/Proxy-with-vite)

2024-07-11 17:55 UTC, lydiacho approved these changes

2024-07-11 17:57 UTC, se0jinYoon approved these changes

2024-07-11 18:41 UTC, merged