[ Design ] 선/후배 약속 리스트 뷰 레이아웃
TEAM-SEONYAK/SEONYAK_CLIENT pull request #44
Opened 2024-07-09 09:31 UTC by se0jinYoon

## #️⃣ Related Issue
Closes #39 

## ✅ Done Task
  - [ ] 선후배 약속 리스트 뷰 레이아웃 잡기

[피그마 뷰입니다]

<img width="156" alt="스크린샷 2024-07-09 오후 6 28 54" src="https://github.com/TEAM-SEONYAK/SEONYAK_CLIENT/assets/109661444/0efa3215-8b5f-4558-b978-a0b54b2b331a">

## ☀️ New-insight

딱히 없슴다

## 💎 PR Point

- 이 부분은 재사용 될 수 있을 것 같아서 따로 구현하려고 제외하고 구현하였습니다.
<img width="295" alt="스크린샷 2024-07-09 오후 6 23 05" src="https://github.com/TEAM-SEONYAK/SEONYAK_CLIENT/assets/109661444/f7dce289-51e9-4e8c-a9b7-bccc3886ceeb">

### 폴더 구조 변경
<img width="267" alt="스크린샷 2024-07-09 오후 6 23 59" src="https://github.com/TEAM-SEONYAK/SEONYAK_CLIENT/assets/109661444/2744b7bf-3f9e-4537-ae0f-72f2085fae94">

- 기존에는 선배, 후배 모두 홈 뷰가 약속 리스트가 뜨는 뷰인 줄 알고 `Home` 폴더 안에 구현하려고 했는데, 기획 디코를 보니 **선배의 홈 뷰**는 `약속 리스트 뷰`, **후배의 홈 뷰**는 `선배 필터링 뷰`라고 합니다. 따라서 `home`보다는  **`promiseList`라는 폴더를 따로 만들어서 약속 리스트 뷰를 구현하는게 맞다고 판단**하여 폴더 구조를 새롭게 만들었습니다.

- `선/후배 약속 리스트 뷰`에서는 선/후배에 따라서 살짝씩만 변경되고 재사용될 수 있는 요소들이 많아서 **`promiseList` 폴더 안에 `common` 폴더를 만들어서 두 뷰에서 사용되는 공통 컴포넌트를 구현**하려합니다.

- 선/후배에 따라 안에 컴포넌트만 갈아끼울 예정이여서 전체 렌더링 페이지는 `PromiseListPage.tsx` 하나로 잡아두었습니다.

=> 의견 있으시면 환영이에요 !!

### nav바 관련
<img width="317" alt="스크린샷 2024-07-09 오후 6 27 15" src="https://github.com/TEAM-SEONYAK/SEONYAK_CLIENT/assets/109661444/8f0df8c9-a6be-4051-b05b-0b62ccdc206a">

하단의 nav바가 예림언니와 제 뷰에서 공통으로 사용됩니다 ! 
버튼을 눌렀을 때 페이지를 바꿔야해서 우선은 퍼블리싱만 해두었고 기능, 스타일 변경 연결은 추후에 진행하도록 하겠습니다!

## 📸 Screenshot

<img width="374" alt="스크린샷 2024-07-09 오후 6 21 45" src="https://github.com/TEAM-SEONYAK/SEONYAK_CLIENT/assets/109661444/748ecc6a-d596-4c7a-bbd8-f2dfc945ad3a">

<img width="376" alt="스크린샷 2024-07-09 오후 6 30 56" src="https://github.com/TEAM-SEONYAK/SEONYAK_CLIENT/assets/109661444/98f79696-ea88-4839-a141-d8ab2819a0e0">

2024-07-09 13:13 UTC, j-nary approved these changes
코드 깔끔하고 너무 좋았어요! 코리 열심히 달고 싶었는데 군더더기없이 갓벽하네오 ... 진짜 열심히 읽었는데 사소하게 트집잡을 만한 게 안 보였던 것 같아요 수고하셨습니당 ! 엄마 체고 !

2024-07-09 17:28 UTC, lydiacho requested changes
수고하셨습니다 코멘트 확인 부탁드려요🤙🏻

2024-07-09 17:28 UTC, lydiacho commented on src/components/commons/Nav.tsx
> +`;
p1) Nav바 fixed로 스크롤뷰에서도 항시 보여야 하는 친구니까 z-index 줘야할 것 같아요!!

2024-07-09 17:28 UTC, lydiacho commented on src/pages/promiseList/commons/PromiseTap.tsx
> +        <TapText $isActive={false}>지난 약속</TapText>
p3) 탭은 다중선택할 수 없고, 하나만 선택 가능하기 때문에, 어떤 탭을 선택했는지를 관리하는 state 하나 만들어두면 좋을 것 같아요! (퍼블리싱 단계라서 신경 안쓰신 것 같아서, 우선 p3로 둡니다! 나중에 추가하셔도 되어용) 

- `activeTap` 라는 state 만들고 
- `$isActive={activeTap === '확정 대기'}` 이런식으로 boolean 넘기기!

2024-07-09 17:28 UTC, lydiacho commented on src/components/commons/Nav.tsx
> +      </TapContainer>
p5) 혹시 상수로 빼고 map 돌리는거 좋아하시나요? 저는 좋아하는 편이라서 제 취향대로 구현했다면 
{ icon: ReactNode, text: string } 이렇게 생긴 **객체의 배열**로 constant 하나를 만들어서 빼주고 

```tsx
NAV_MENU_LIST.map(({icon, text}) => <TapContainer>{icon}<TapContent>{text}</TapContent></TapContainer>
```
이런식으로 구현할 것 같슴다 
취향 차이라고 생각해서 참고참고 ~~

2024-07-10 07:21 UTC, se0jinYoon commented on src/pages/promiseList/commons/PromiseTap.tsx
> +        <TapText $isActive={false}>지난 약속</TapText>
네네 ! 기능 연결할 때 작업해두겠습니다 ㅎㅎ

2024-07-10 07:21 UTC, se0jinYoon commented on src/components/commons/Nav.tsx
> +`;
반영완 !

2024-07-10 07:22 UTC, se0jinYoon commented on src/components/commons/Nav.tsx
> +      </TapContainer>
오호 저도 이 구조 굉장히 좋아하는데요 , 이 부분은 선택되지 않은 값들의 경우에는 회색 svg로 되고, 선택되면 검정색으로 변경되기 때문에 기능 브랜치에서 변경해두겠습니다-!-!

2024-07-10 08:23 UTC, lydiacho approved these changes

2024-07-10 08:28 UTC, merged