[Init] PR Size Labeler
TEAM-SEONYAK/SEONYAK_CLIENT pull request #5
Opened 2024-06-30 20:10 UTC by j-nary

| 항목      | 내용                          |
| --------- | ----------------------------- |
| ⏰ Time | 2H          |
| 🌱 Page |  초기세팅                |
| #️⃣ Issue Number | #4                 |

## ☀️ New-insight

1. 라벨이 자동적으로 생성되지 않을 때
![image](https://github.com/TEAM-SEONYAK/SEONYAK_CLIENT/assets/83453646/dd683496-39e5-4cba-a796-c8637c4eb77f)
레포 Settings > Actions > General > Workflow permissions
위의 사진과 같이 바꿔야 수동으로 라벨을 설정하지 않아도 자동 추가된다는 것을 알아냈다!

2. Marketplace에서 PR size labeler (diff)를 선택한 이유
https://github.com/marketplace?query=size+labeler
marketplace에는 해당 기능을 제공하는 도구가 7개 정도있는데 `package.json`, `*.lock` 같은 파일들은 PR 사이즈에 포함되지 않았으면 했다.
그 중, [pr-size-labeler-diff](https://github.com/marketplace/actions/pr-size-labeler-diff) 가 유일하게 `excluded_files` 옵션이 있어서 선택했다.

3. 느낀점
너무 생소한 개념이고 구글에 쳐도 참고자료가 많이 없길래 자료조사하는데 오래 걸렸다.
근데 그냥 간단한 action 기능이라 참고자료가 많이 없었던 것이었다.
코드라인 24번째에서 서진언니의 코리를 받을 것 같다 유유 😭

## ⁉️ Question

## 📸 Screenshot

<img width="584" alt="image" src="https://github.com/TEAM-SEONYAK/SEONYAK_CLIENT/assets/83453646/e39deed5-ecff-4524-921e-3752b79c111d">
<img width="928" alt="image" src="https://github.com/TEAM-SEONYAK/SEONYAK_CLIENT/assets/83453646/ba155a32-a811-4b82-a991-9e1072dee2ff">
저의 개인 레포에서 test한 스크린샷입니다.

2024-07-01 09:33 UTC, se0jinYoon requested changes

2024-07-01 09:33 UTC, se0jinYoon commented on .github/workflows/labeler.yml
> +    steps:
p1) 제가 마일에서 세팅했을 때도 검사는 되고 라벨이 자동으로 생성이 안됐었는데, 그래서 permission 속성을 여기에 추가해두고, 라벨 직접 만들어뒀었는데 (ex. size/xs, size/s, size/m … 각자 라벨 세팅해뒀었음)
확인 한 번 해보시면 좋을 것 가타요!

[참고 PR!](https://github.com/Mile-Writings/Mile-Client/pull/27)

2024-07-01 09:33 UTC, se0jinYoon commented on .github/workflows/labeler.yml
> +            이슈를 여러개 파서 PR을 분리하는게 어떠싱지 ㅋ
p5) ㅋㅋㅋㅋㅋ굿 조타~

2024-07-01 14:19 UTC, ijieun approved these changes
멘트가 귀여워요 생소한 개념이었을텐데도 잘 적용하셨네요! 고생하셨습니당!!

2024-07-01 15:46 UTC, lydiacho reviewed
여러 선택지 알아보고 필요에 따라 선택한거 너무 좋네요 잘 적용 됐음 좋겠다 !! 

+ 진이가 템플릿 담당이어서 관련된 의견 여기 코리에 남겨요! 단순히 제 개인적인 의견이고 다른 분들의 의견도 궁금합니다 ㅎㅎ 

**[ PR Template 관련 리뷰 ]** 

1. `Time` : **제거하는거** 어떨까요? 세미나 과제에서는 해당 과제를 어느정도 고민했는지, 어느정도 난이도로 느꼈는지 팟장이 파악할 수 있는 지표가 될 수 있지만, 빠르게빠르게 같이 작업을 쳐내는 앱잼의 환경에서는 해당 작업 소요시간이 얼마나 되는지는 크게 중요하지 않을 것 같아요. 작업시간 재기도 번거롭구요! 
2. `Page` : 요건 어느 페이지에 속하는 작업인지 적어주는거죠?? 이 정보를 명시해주는건 너무 좋은데, 이렇게 내부에 작성해주기보다 PR 제목에 작성해주거나, label로 달아주는건 어때요? 
- ex1 ) PR제목 컨벤션 : [Prefix] Page명 - 작업내용
- ex2) 각 Page별 label 생성 -> 라벨을 통해 Page별로 PR 필터링해서 볼 수 있다는 장점! 

둘다 적용한 예시 
![스크린샷 2024-07-02 오전 12 50 27](https://github.com/TEAM-SEONYAK/SEONYAK_CLIENT/assets/81505421/9dbdf48a-ec88-4e4e-8cf6-924895a3f8d0)


3. `Issue Number` : 현재는 issue 번호만 #번호 이렇게 적어주고 있는데요! PR 우측의 Development를 보면 issue가 잘 연동되지 않는다는걸 알 수 있어요. 여기서 꿀팁은 `Closes #번호` 이렇게 작성해주면 해당 이슈가 PR과 연결될 뿐만 아니라, PR을 merge 했을 때 자동으로 연결되어있는 PR이 close 됩니다! 
따라서 template에 Closes # 요렇게 명시해두고 뒤에 이슈번호만 바로바로 붙일 수 있게 해두는건 어떨까요?? 

- 템플릿 예시
![스크린샷 2024-07-02 오전 12 41 52](https://github.com/TEAM-SEONYAK/SEONYAK_CLIENT/assets/81505421/5e6ea6bb-b137-4047-b2de-e3db63d48c63)

- 사용 예시 
![스크린샷 2024-07-02 오전 12 41 34](https://github.com/TEAM-SEONYAK/SEONYAK_CLIENT/assets/81505421/da9c28db-2d60-43e7-ad99-78b2d3c785d3)


4. `Question` -> `PR Point` 혹은 `Comment` 로 수정하는거 어떨까요? 
Question은 말그대로 작업과 관련된 질문거리를 남기는 카테고리인건데, 새로 배운것(New insight), 질문거리(Question), 스크린샷 외에, 
- 내가 해당 작업을 하면서 겪었던 트러블 슈팅 / 깊게 고민한 로직 설명 
- 공통 컴포넌트를 제작한 PR의 경우, 다른 개발자들에게 공통 컴포넌트 사용방법을 알려줄 수 있음 ([예시](https://github.com/TEAM-MODDY/moddy-web/pull/37))
- 이 외에, 이 부분 집중해서 코드리뷰해주세요 ~ 하고 부탁 

이런 내용들이 담길 곳이 필요할 것 같아요! 
따라서 Question 외에 하나의 카테고리를 추가하거나, Question 카테고리명을 대체하면 좋을 것 같습니다 :) 

수고가많아요!! 의견 환영합니다 🥰

2024-07-01 17:38 UTC, yarimu commented
와아,, 어려워 보이는 것도 뚝딱 해내는 진님,, 멋집니다..✨

**[숭님이 말씀하신 pr관련 의견]**

- `Time`
: 저의 경우는 가늠이 안된다는 점에서 time개념이 어려웠던 거 같아서 빼는 것에 동의합니다..!
- `Page`
: 둘 다 적용된 이미지 보니까 직관적이고 깔끔해서 좋은 거 같습니다..!
- `Issue Number`
: 저도 합세때 그렇게 해서 좋았습니다!
- `Question` -> To reviewers
: 이 부분에 대해서 저는 pr 작성하면서 소통을 위한 창구이다 보니  To reviewers면 어떨까? 생각했던 것 같아요..!

**[이슈 템플릿 관련]**
: 말 할까 말까 하다가.. 늦게 리뷰로 의견낸 점 죄송합니다.
만약 이슈 템플릿 변경이 채택된다면,, 제가 변경하도록 하겠습니다..!
합세때 유용했던 이슈 템플릿인데요, 다음은 작성화면입니다..!

<img width="1470" alt="스크린샷 2024-07-02 오전 2 18 20" src="https://github.com/TEAM-SEONYAK/SEONYAK_CLIENT/assets/157878428/0bd6f26c-573e-412f-9250-40b0621d8a00">

어떠신가요?? 각 항목의 내용만 기존의 이슈템플릿처럼 작업내용, TODO로 바꾸자는 서진님의 의견이있었습니다!
이 부분에 대해서 다들 의견이 궁금해요~

정리라고 하긴 머쓱하지만 나중에 쓰고 싶어서 이슈템플릿관련 따로 정리해두었던 노션 입니다.
 
https://yarimu.notion.site/a7223c3f00cf4b19b4bec5fe2484fc34?pvs=4

2024-07-03 13:21 UTC, ijieun commented
승희님 의견 동의합니다!
저도 PR을 보낼때마다 시간 측정하기에 번거로움이 있을 것 같아 Time 제거하는거 찬성합니다! Page는 필터링으로 한눈에 보기에 편할것 같아서  PR 라벨링으로 작성하는 것 좋은 것 같습니다!
Closes #번호로 적어두면 자동으로 같이 닫히는 기능이 있는지 첨 알았네요!
Question을 PR Point로 변경하는 것도 PR을 중점적으로 볼 수 있을 것 같아 좋은것 같습니다~! 👍🏻

2024-07-03 16:28 UTC, merged

2024-07-03 19:51 UTC, j-nary commented on .github/workflows/labeler.yml
> +            이슈를 여러개 파서 PR을 분리하는게 어떠싱지 ㅋ
앗싸 !!!