[ Feat ] SeniorProfilePage TimeSelect 구현
TEAM-SEONYAK/SEONYAK_CLIENT pull request #71
Opened 2024-07-10 19:08 UTC by j-nary

## #️⃣ Related Issue
Closes #33 

## ✅ Done Task
  - [x] profile 데이터 객체 연결
  - [x] TimeSelect 뷰 퍼블리싱
  - [x] ToggleButton funnel 구조 구현
  - [x] Dropdown 기능 구현
  - [x] Dropdown 비활성화 기능 추가
  - [ ] Dropdown Warning 기능 추후 구현 예정

## ☀️ New-insight

- 왜 오류가 날까?
    
    ```jsx
      const initialValue = profile.preferredTimeList[category][day][0][timeCategory];
    ```
    
- 해결방법1.
    
    ```jsx
    //tsconfig.app.json
    "strict": true,
    ```
    
    - `"strict": false,` 로 바꾼다
    - 언니들한테 맞겠지?
- 해결방법2.
    
    - 객체 자체를 드릴링X
        
        → 부모에게서 필요한 값만 받아오게 하자
        
    - 전체 코드를 드롭다운 컴포넌트에서 만들어서 사용하는 것은 순수성을 너무 해친다
        
        → 부모가 적당히 조립해서 값 변경에 필요한 인자만 넣어서 쓰도록 하자 !!
        
    - 해결 !!!
    
    ```jsx
    const TimeAlldays = ({ profile, setProfile }: profilePropType) => {
      const dayOfWeekSetProfile = (key: dayType) => (timeCategory: 'startTime' | 'endTime') => (selectedValue: string) =>
        setProfile((prev) => ({
          ...prev,
          preferredTimeList: {
            ...prev.preferredTimeList,
            dayOfWeek: {
              ...prev.preferredTimeList.dayOfWeek,
              [key]: prev.preferredTimeList.dayOfWeek[key].map((time: preferredTimeType) => ({
                ...time,
                [timeCategory]: selectedValue,
              })),
            },
          },
        }));
    
      return (
        <Wrapper>
          {WEEKENDS.map((w, idx) => (
            <Container key={idx}>
              <CategoryText>{w}</CategoryText>
              <DurationSelect
                variant="secondary"
                isLatter={idx > 3}
                selectValue={profile.preferredTimeList.dayOfWeek[w][0]}
                setProfile={dayOfWeekSetProfile(w)}
              />
            </Container>
          ))}
        </Wrapper>
      );
    };
    ```
    
    → 이런식으로 부모에서 조립 !!! 항상 순수성 유지할 수 있게 prop으로는 필요한 값만 넘겨주기
   

## 💎 PR Point

![image](https://github.com/TEAM-SEONYAK/SEONYAK_CLIENT/assets/83453646/1a47fff7-bf99-4ed3-90c3-0d2b44b8f3ed)
- x버튼 눌러서 비활성화 시키면 profile 데이터는 시작 시간으로 잘 바뀌는데 UI는 안 바뀐다.
- `DeleteIcon`을 눌러서 `handleDelete`가 호출되면 Profile이 바뀐다
    
    → 바뀐 것 까지 확인
    
    그러면 Profile 값이 쓰이는 모든 요소가 리렌더링 돼야하는게 아닌가?
    
    → 왜 시작 시간이라고 바뀌지 않지?
 - DropDown 에서 defaultValue가 반영 X
- 리렌더링 된다고 언마운트 때 사용했던 걸 재사용하지는 X
- 이미 state로 독립되어버림
- useEffect에 isActive 의존성 추가해서 값 수동으로 바꿔줘야겠다 (해결!)
    
    ```jsx
      useEffect(() => {
        setSelectedValue(defaultValue);
      }, [isActive]);
    ```
svgr 형식

```jsx
const ArrowDownIcon = styled(ArrowDownIc)<{ $isActive: boolean }>`
  fill: ${({ $isActive }) => ($isActive ? '#A2A7B0' : '#E7EAF2')};
`;
```

- fill 속성이 안 먹을 때 !
    
    ```jsx
    <svg width="34" height="35" viewBox="0 0 34 35" fill="none" xmlns="http://www.w3.org/2000/svg">
    <g id="ic_arrow_down_mg">
    <path id="Vector 2" d="M12.5035 14.3327H21.496C21.9156 14.3327 22.1506 14.8162 21.8914 15.1461L17.3951 20.8687C17.1938 21.1249 16.8057 21.1249 16.6044 20.8687L12.1081 15.1461C11.8489 14.8162 12.0839 14.3327 12.5035 14.3327Z" fill="#A2A7B0"/>
    </g>
    </svg>
    ```
    
    → path 맨 뒤에 fill을 삭제해주면 된다
    

트러블 슈팅

- 또 뭔 오류냐 딸기
    
    ![image](https://github.com/TEAM-SEONYAK/SEONYAK_CLIENT/assets/83453646/2245a7f0-bbd4-49fa-af5d-6d1cb423a7b5)
    
- 아래 코드에서 나는 오류 같아 보임
    
    ```tsx
    const ArrowDownIcon = styled(ArrowDownIc)<{ $isActive: boolean }>`
      fill: ${({ $isActive }) => ($isActive ? '#A2A7B0' : '#E7EAF2')};
    `;
    ```
    
- svg 속성은 대문자와 특수기호를 사용하면 안 되나보다!
- 아래와 같이 수정했다
    
    ```jsx
    const ArrowDownIcon = styled(ArrowDownIc)<{ isactive: boolean }>`
      fill: ${({ isactive }) => (isactive ? '#A2A7B0' : '#E7EAF2')};
    `;
    ```
    
- 또 아래와 같은 오류가 …
    
    ![image](https://github.com/TEAM-SEONYAK/SEONYAK_CLIENT/assets/83453646/bd1cbbfc-2bad-49f1-a77f-2b5fea0b3a11)
    
    - boolean이면 안 된대 그래서 string으로 고쳐줌
    - 왜 boolean이 안 될까?
    - styled-compoents는 Boolean 값을 문자열로 변환하여 처리하기 때문에 예상치 못한 동작을 초래할 수 있다고 하네요!
    - 또 html에는 boolean 타입이 없어서도 있는 것 같습니당
- 최종본
    
    ```jsx
    <ArrowDownIcon isactive={isActive.toString()} />
    
    const ArrowDownIcon = styled(ArrowDownIc)<{ isactive: string }>`
      fill: ${({ isactive }) => (isactive === 'true' ? '#A2A7B0' : '#E7EAF2')};
    `;
    ```
 - Header도 수정했슴니닥람쥐
## 📸 Screenshot

![image](https://github.com/TEAM-SEONYAK/SEONYAK_CLIENT/assets/83453646/782bf410-cc31-48a4-965d-626840f89a5c)
 - profile 잘 바뀌는 거 확인했습니당
 - 주중/주말 선택 -> 모든 요일 선택 -> 주중/주말 선택 다시해도 state 저장될 수 있게 !!

2024-07-12 06:51 UTC, se0jinYoon requested changes
코멘트 몇개만 확인해주세요 ~ 
로직 잘 짰다 최고만고다 ~

2024-07-12 06:51 UTC, se0jinYoon commented on src/pages/seniorProfile/components/common/DropDown.tsx
> +  }, []);
p3)저도 공통 모달 구현할 때 이런식으로 했는데 승히가 제 코리에 달아준 부분 반영해서 바꿨어요 ! 진이도 적용해보면 좋을 것 같아서 !! 승히 코리 복붙해오겟음

> 현재 backdrop 클릭 로직을 구현하기 위해
>
> Modal 영역이 아닌 곳인지 체크
> useEffect을 활용
> 이렇게 구현되고 있는데요!
> 사실 사용자의 액션으로 인해 발생하는 이벤트는 useEffect를 통해 구현하는 것을 최대한 지양해야 한다고 해요
> 따라서 커스텀훅을 사용하지 않는 방향으로 가는 것이 좋을 것 같은데,
> 그러기 위해 Modal 영역이 아닌 곳인지 체크 하지 않고, 그냥 모달의 backdrop이 되는 어두운 영역을 모달 아래에 하나 더 깔아서 positon, z index를 통해 겹쳐서 배치시켜주고, 그 backdrop에 클릭 핸들러를 붙이면 될 것 같아요!
>
> 한번 이런 방식으로 구현해보셔도 좋을 것 같아요 :) 👍🏻

[공통 모달 pr](https://github.com/TEAM-SEONYAK/SEONYAK_CLIENT/pull/36)

2024-07-12 06:51 UTC, se0jinYoon commented on src/pages/seniorProfile/components/common/DurationSelect.tsx
> +import PlusIc from '@assets/svgs/ic_plus_btn.svg?react';
p1) 이거 왜 여기서 import해서 사용하나요 ? index.ts에서 export한 값으로 사용하는 걸루 바꿔주세여 ! 컨벤션!

2024-07-12 06:51 UTC, se0jinYoon commented on src/pages/seniorProfile/components/common/DropDown.tsx
> +import ArrowDownIc from '../../../../assets/svgs/ic_arrow_down_mg.svg?react';
p1) 어라라 여기두 그러네 ?

2024-07-12 06:51 UTC, se0jinYoon commented on src/pages/seniorProfile/components/common/DurationSelect.tsx
> +      <WaveText $isDefault={variant === 'default'} $isActive={isActive}>
p5) 네이밍 귀엽다

2024-07-12 06:51 UTC, se0jinYoon commented on src/pages/seniorProfile/components/common/DurationSelect.tsx
> +  padding-left: ${({ $isDefault }) => ($isDefault ? '0.9rem' : '0.7rem')};
p2) 여기 하나로 합쳐서 쓸 수 있을 거 같아요~

2024-07-13 13:33 UTC, j-nary commented on src/components/commons/FullButton.tsx
> +  transform: translateX(-50%);
가운데 위치시켜두기 위함임니다 ! 버튼 fixed로 빼고 정 가운데 위치 시켰어용

2024-07-13 13:34 UTC, j-nary commented on src/pages/seniorProfile/SeniorProfilePage.tsx
> +        return <TimeSelect profile={profile} setProfile={setProfile} setIsNextActive={setIsNextActive} />;
넹면 !!

2024-07-13 13:35 UTC, j-nary commented on src/pages/seniorProfile/components/common/DropDown.tsx
> +    if (isActive) setIsSelectDown((prev) => !prev);
넹면 !! 감사링 !! 💓

2024-07-13 13:37 UTC, j-nary commented on src/pages/seniorProfile/components/common/DropDown.tsx
> +import ArrowDownIc from '../../../../assets/svgs/ic_arrow_down_mg.svg?react';
수정 완 !!

2024-07-13 13:39 UTC, j-nary commented on src/pages/seniorProfile/components/common/DurationSelect.tsx
> +import PlusIc from '@assets/svgs/ic_plus_btn.svg?react';
넹면 !! 수정 완 햇슴둥 >_< 💓

2024-07-13 13:57 UTC, j-nary commented on src/pages/seniorProfile/components/common/DurationSelect.tsx
> +      <WaveText $isDefault={variant === 'default'} $isActive={isActive}>
언니 나는요?

2024-07-13 13:59 UTC, j-nary commented on src/pages/seniorProfile/components/common/DurationSelect.tsx
> +  padding-left: ${({ $isDefault }) => ($isDefault ? '0.9rem' : '0.7rem')};
넹 !! 반영 완료햇슴둥 !!

2024-07-13 18:46 UTC, j-nary commented on src/pages/seniorProfile/components/common/DropDown.tsx
> +  }, []);
반영 완료했습니다 !! 아티클도 썼어용 구경오실래용? [useEffect로 backdrop 구현하면 안 되는 이유](https://velog.io/@jnary/React-useEffect로-backdrop-구현하면-안-되는-이유-kr7rk2xf)

2024-07-15 09:59 UTC, lydiacho approved these changes
전반적으로 코드는 잘 짠거같아요 클론해서 작동 체크하고 싶었는데 레이아웃이 깨져있어서 레이아웃 온전한 마지막 PR로 체크하겠습니다 LGTM!

2024-07-15 09:59 UTC, lydiacho commented on src/assets/svgs/index.tsx
p1) pages > login > LoginPage.tsx 에서 GoogleIc import문에서 에러가 발생하고 있어요! 여기 index.tsx에서 GoogleIc를 추출안해주고있네요. 이거 때문에 실행이 안돼서 요기 아이콘 export 추가해주면 좋을 것 같아요 ~~

2024-07-15 12:50 UTC, j-nary commented on src/assets/svgs/index.tsx
네 !! 알겠슴니당 !!

2024-07-15 13:43 UTC, merged