[ Feat ] Onboarding 페이지 학과선택, 재직인증 Step 바텀시트 구현
TEAM-SEONYAK/SEONYAK_CLIENT pull request #88
Opened 2024-07-12 19:03 UTC by j-nary

## #️⃣ Related Issue
Closes #84 

## ✅ Done Task
  - [ ] 바텀시트 공통 컴포넌트 구현
  - [ ] 학과선택 바텀시트 퍼블리싱
  - [ ] 학과선택 바텀시트 선택된 값 상태 연결
  - [ ] 재직인증 바텀시트 퍼블리싱
  - [ ] 재직인증 바텀시트 선택된 값 상태 연결

## ☀️ New-insight

없슴다!

## 💎 PR Point

없슴다!

## 📸 Screenshot

https://github.com/user-attachments/assets/cbfd84f3-3019-4dea-97d2-fb1f6139b75d

2024-07-13 13:17 UTC, se0jinYoon reviewed
lgtm~

2024-07-13 23:17 UTC, j-nary commented on src/pages/onboarding/components/BottomSheet.tsx
> +const BottomSheet = ({ handeClose, children }: bottomSheetPropType) => {
헉 감사링 !!! 💓💓💓

2024-07-15 11:24 UTC, lydiacho requested changes
LGTM 
이거 머지하기 전에 예림언니가 만들어둔 바텀시트 콘텐츠 넣어서 완성시켜주면 좋을 것 같아요!

2024-07-15 11:24 UTC, lydiacho commented on src/pages/onboarding/components/SearchBox.tsx
> +  width: 33.5rem;
<img width="619" alt="image" src="https://github.com/user-attachments/assets/560813de-3c65-4b2a-834d-ed59f21af65a">

p1) 이거 이렇게 width 박아버리면 기기별 호환성을 지키지 못해요. 만약 이렇게 너비 고정하고 싶다면, margin: 0 auto 줘서 중앙정렬 맞춰줘야할 것 같습니다. 그런데 아마 디자이너들은 너비가 고정이고 여백이 늘어나는 형태보다, 여백이 고정이고 너비가 늘어나는 걸 기대할거예요. 그래서 width 지정은 빼줘야할 것 같아요

2024-07-15 16:35 UTC, merged